apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-greeting
  labels:
    {{- template "labels" . }}
spec:
  replicas: {{ .Values.greeting.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-greeting
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-greeting
    spec:
      containers:
      - name: {{ .Release.Name }}-greeting
        image: {{ .Values.greeting.image }}:{{ .Values.docker.tag }}
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
          name: http
        readinessProbe:
          httpGet:
            path: /resources/greeting
            port: 8081
          initialDelaySeconds: 50
          periodSeconds: 5
